name: pecotmr
channels:
  - dnachun
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - clangdev
  - gsl
  - bioconductor-bioccheck
  - r-devtools
  - r-rcmdcheck
  - r-covr
  - r-tidyverse
