[project]
name = "r-pecotmr"
channels = ["dnachun", "conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[system-requirements]
libc = { family="glibc", version="2.17" }

[tasks]
devtools_document = "R -e 'devtools::document()'"
devtools_test = "R -e 'devtools::test()'"
codecov = "R -e 'covr::codecov(quiet = FALSE)'"
rcmdcheck = "R -e 'rcmdcheck::rcmdcheck()'"
bioccheck_git_clone = "R -e 'BiocCheck::BiocCheckGitClone()'"
bioccheck = "R -e 'BiocCheck::BiocCheck()'"

[dependencies]
"gsl" = "*"
"bioconductor-bioccheck" = "*"
"r-devtools" = "*"
"r-rcmdcheck" = "*"
"r-covr" = "*"
"r-tidyverse" = "*"
