name: Post-merge actions

on:
  pull_request_target:
    types: [closed]
    paths-ignore:
      - .github/*
      - .gitignore
      - README.md

jobs:
  update_coverage_badge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create TOML from recipe
        run: .github/workflows/create_toml_from_yaml.sh ${GITHUB_WORKSPACE}

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.2

      - name: Check unit test code coverage
        run: pixi run codecov
