name: Update documentation

on:
  pull_request_target:
    paths-ignore:
      - .github/*
      - .gitignore
      - README.md

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Create TOML from recipe
        run: .github/workflows/create_toml_from_yaml.sh ${GITHUB_WORKSPACE}

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.2

      - name: Run unit tests
        run: pixi run devtools_document

      - name: Commit changes to documentation
        uses: EndBug/add-and-commit@v9
        with:
          push: true
          message: Update documentation
